In [1]:
!pip install numpy --upgrade --quiet

You should consider upgrading via the '/home/krishna/anaconda3/bin/python -m pip install --upgrade pip' command.


In [2]:
!pip install numpy

You should consider upgrading via the '/home/krishna/anaconda3/bin/python -m pip install --upgrade pip' command.


In [3]:
!pip install --upgrade pip

     |████████████████████████████████| 1.5 MB 617 kB/s eta 0:00:01
  Attempting uninstall: pip
    Found existing installation: pip 21.1.2
    Uninstalling pip-21.1.2:
      Successfully uninstalled pip-21.1.2


In [4]:
!pip install numpy

In [8]:
import numpy as np

In [9]:
kanto=np.array([73,67,43])

In [10]:
kanto

array([73, 67, 43])

In [13]:
weights=np.array([0.3,0.2,0.5])


In [14]:
weights

array([0.3, 0.2, 0.5])

In [15]:
type(kanto)

numpy.ndarray

In [16]:
type(weights)

numpy.ndarray

In [18]:
weights[0]

0.3

In [19]:
kanto[2]

43

In [20]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [21]:
np.dot(kanto,weights)

56.8

In [24]:
kanto


array([73, 67, 43])

In [25]:
weights

array([0.3, 0.2, 0.5])

In [26]:
kanto*weights

array([21.9, 13.4, 21.5])

In [27]:
(kanto*weights).sum()

56.8

In [29]:
kanto @ weights

56.8

In [33]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7ff56cfd2730>)

In [37]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)


In [38]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [40]:
climate_data.shape

(10000, 3)

In [42]:
weights=np.array([0.3,0.2,0.5])

In [43]:
yields=climate_data @ weights

In [44]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [46]:
yields.shape

(10000,)

In [55]:
climate_results=np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [56]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [65]:
np.savetxt('climate_results.txt',climate_results,fmt='%.2f',header='temperaure,rainfall,humidity,yeild_appples',comments=' ')

In [66]:
arr2=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11],[14,15,16,17]])


In [67]:
arr2

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [72]:
arr5=np.array([[7,8],[7,8],[7,8],[7,8]])

In [92]:
url1 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans1.txt'
url2 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans2.txt'
url3 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans3.txt'

In [93]:
from urllib.request import urlretrieve

In [99]:
import os

In [100]:
os.getcwd()

'/home/krishna'

In [101]:
os.listdir('.')

['File handling.ipynb',
 'Untitled1.ipynb',
 '.pki',
 'Videos',
 '.sudo_as_admin_successful',
 '.anaconda',
 'file.txt',
 '.ssh',
 '.local',
 'c++',
 'jupyter',
 'anaconda3',
 '.config',
 '.gvfs',
 'Desktop',
 'git.tar.gz',
 'data visualzation.ipynb',
 'Public',
 'env_site',
 '.thunderbird',
 '.cache',
 'Templates',
 'Untitled2.ipynb',
 '.bash_logout',
 'snap',
 '.zoom',
 'Music',
 'IdeaProjects',
 '.gnupg',
 '.mysql_history',
 '.ipython',
 '.continuum',
 'git-2.23.0',
 '.jupyter',
 'Documents',
 'Untitled.ipynb',
 'Pictures',
 '.mozilla',
 'file1.txt',
 '.conda',
 'climate_results.txt',
 '.gphoto',
 'Downloads',
 '.wget-hsts',
 '.java',
 '.ICEauthority',
 '.dbus',
 '.bash_history',
 '.bashrc',
 '.profile',
 '.gitconfig',
 'PycharmProjects',
 '.vscode',
 'climate.txt',
 'get-pip.py',
 '.condarc',
 '.ipynb_checkpoints',
 '10.30.27.62:8000',
 '.android',
 'examples.desktop']

In [102]:
os.listdir('/usr')

['libexec', 'sbin', 'bin', 'lib', 'games', 'src', 'include', 'share', 'local']