In [1]:
import numpy as np

In [2]:
x=[[1,2,3,4],[3,4,6,10]]

In [3]:
#numpy cn abe any dimension
#x[row:column]
y=np.array(x)
print(y)

[[ 1  2  3  4]
 [ 3  4  6 10]]


In [4]:
y[:,1:3] #y[row_start:row_end,column_start:column_end]


array([[2, 3],
       [4, 6]])

In [5]:
y.ndim

2

In [6]:
y.shape

(2, 4)

In [7]:
x1=[[[1,2,3,4],[3,4,6,10]],[[1,2,3,4],[3,4,6,10]]]

In [8]:
y1=np.array(x1)

In [9]:
print(y1)

[[[ 1  2  3  4]
  [ 3  4  6 10]]

 [[ 1  2  3  4]
  [ 3  4  6 10]]]


In [10]:
y1[:,:2,:]

array([[[ 1,  2,  3,  4],
        [ 3,  4,  6, 10]],

       [[ 1,  2,  3,  4],
        [ 3,  4,  6, 10]]])

In [11]:
y1[:,:2,:2]

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [12]:
np.random.seed(0)
k=np.random.rand(2,3,3,4)
k

array([[[[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
         [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
         [0.96366276, 0.38344152, 0.79172504, 0.52889492]],

        [[0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
         [0.0202184 , 0.83261985, 0.77815675, 0.87001215],
         [0.97861834, 0.79915856, 0.46147936, 0.78052918]],

        [[0.11827443, 0.63992102, 0.14335329, 0.94466892],
         [0.52184832, 0.41466194, 0.26455561, 0.77423369],
         [0.45615033, 0.56843395, 0.0187898 , 0.6176355 ]]],


       [[[0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
         [0.3595079 , 0.43703195, 0.6976312 , 0.06022547],
         [0.66676672, 0.67063787, 0.21038256, 0.1289263 ]],

        [[0.31542835, 0.36371077, 0.57019677, 0.43860151],
         [0.98837384, 0.10204481, 0.20887676, 0.16130952],
         [0.65310833, 0.2532916 , 0.46631077, 0.24442559]],

        [[0.15896958, 0.11037514, 0.65632959, 0.13818295],
         [0.19658236, 0.36872517, 0.82099323

In [13]:
k[:,:,:3,:2]

array([[[[0.5488135 , 0.71518937],
         [0.4236548 , 0.64589411],
         [0.96366276, 0.38344152]],

        [[0.56804456, 0.92559664],
         [0.0202184 , 0.83261985],
         [0.97861834, 0.79915856]],

        [[0.11827443, 0.63992102],
         [0.52184832, 0.41466194],
         [0.45615033, 0.56843395]]],


       [[[0.61209572, 0.616934  ],
         [0.3595079 , 0.43703195],
         [0.66676672, 0.67063787]],

        [[0.31542835, 0.36371077],
         [0.98837384, 0.10204481],
         [0.65310833, 0.2532916 ]],

        [[0.15896958, 0.11037514],
         [0.19658236, 0.36872517],
         [0.83794491, 0.09609841]]]])

In [14]:
k[:,:1,:3,:2]

array([[[[0.5488135 , 0.71518937],
         [0.4236548 , 0.64589411],
         [0.96366276, 0.38344152]]],


       [[[0.61209572, 0.616934  ],
         [0.3595079 , 0.43703195],
         [0.66676672, 0.67063787]]]])

In [15]:
np.ones_like(k)

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [16]:
x=np.random.randint(2,10,(2,3))
y=np.random.randint(2,10,(2,2))

In [17]:
k=np.zeros_like(x)

In [18]:
k[:,:2]=y

In [19]:
np.eye(3)# it creates 2d array like idenity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3,4)#it will print the elements where i=j and rest of thm are 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [21]:
#numpy.diag it will helpfu while doing algebric functions
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
np.diag([1,2,3],1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [23]:
a=np.array([[1,2],[3,4]])
np.diag(a)

array([1, 4])

In [24]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
np.random.seed(0)
b=np.random.rand(2,2,2,3)
b


array([[[[0.5488135 , 0.71518937, 0.60276338],
         [0.54488318, 0.4236548 , 0.64589411]],

        [[0.43758721, 0.891773  , 0.96366276],
         [0.38344152, 0.79172504, 0.52889492]]],


       [[[0.56804456, 0.92559664, 0.07103606],
         [0.0871293 , 0.0202184 , 0.83261985]],

        [[0.77815675, 0.87001215, 0.97861834],
         [0.79915856, 0.46147936, 0.78052918]]]])

In [27]:
np.indices((2,4,3))

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]],


       [[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]]])

In [28]:
x=np.arange(10)

In [29]:
#x.shape=(2,5)# now x is 2-dimensional
x[1:7:2]

array([1, 3, 5])

In [30]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
y=np.arange(35).reshape(5,7)

In [32]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [33]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [34]:
x=np.arange(10,1,-1)

In [35]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [36]:
x[np.array([3,3,1,8])]

array([7, 7, 9, 2])

In [37]:
x[np.array([[1,1],[3,3]])]

array([[9, 9],
       [7, 7]])

In [38]:
y=np.arange(35).reshape(5,7)

In [39]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [40]:
y[np.array([0,2,4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [41]:
#boolean or mask index arrays
b=y>20
y[b]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [42]:
b[:,5]#it will go by row size and it will return the true or false value


array([False, False, False,  True,  True])

In [43]:
y[b[:,5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [44]:
x=np.arange(30).reshape(2,3,5)

In [45]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [46]:
y[np.array([0,2,4]),1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [47]:
y[:,1:3][np.array([0,2,4]),:]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [48]:
b=y>20# it will give the greatest elements in the y

In [49]:
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [50]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [51]:
y.shape # it will give the shape of the y


(5, 7)

In [52]:
y[:,np.newaxis,:].shape

(5, 1, 7)

In [53]:
y.shape

(5, 7)

In [54]:
# adding new axis to the element
x=np.arange(5)

In [55]:
x[:,np.newaxis]+x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [56]:
z=np.arange(81).reshape(3,3,3,3)

In [57]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [58]:
 z[1,...,1]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [59]:
z[2,:,:,0]# it will covert the columns into the rows ..

array([[54, 57, 60],
       [63, 66, 69],
       [72, 75, 78]])

In [60]:
#assinging values to the index arrays
x=np.arange(10)

In [61]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x[2:7]=1#it will convert the all index values into the 1's

In [63]:
x

array([0, 1, 1, 1, 1, 1, 1, 7, 8, 9])

In [64]:
x[2:7]=np.arange(5)

In [65]:
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

In [66]:
x[1]=1.2

In [67]:
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])

In [68]:
x=np.arange(0,50,10)

In [69]:
x[np.array([1, 0, 3, 0])] += 1#it will go through the indexes

In [70]:
x

array([ 1, 11, 20, 31, 40])

In [71]:
indices=(1,1,1,1)

In [72]:
z[indices]

40

#numpy i/o 



In [73]:
data=u"1,2,3\n4,5,6"
#spliting the lines to columns
from io import StringIO

In [74]:
np.genfromtxt(StringIO(data), delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [75]:
data=u'\n'.join(str(i) for i in range(10))

In [76]:
 np.genfromtxt(StringIO(data),)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [77]:
np.genfromtxt(StringIO(data),skip_header=4,skip_footer=5) #skip header it will skip the header and skip footer it will skip the header

array(4.)

In [78]:
data=u"1,2,3\n4,5,6"
np.genfromtxt(StringIO(data),delimiter=",",usecols=(0,-1))#usecols=(0,-1))

array([[1., 3.],
       [4., 6.]])

In [79]:
np.genfromtxt(StringIO(data),delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

In [80]:
data=StringIO(u"1 2 3\n 4 5 6")
np.genfromtxt(data, dtype=[(_, int) for _ in "abc"])





array([(1, 2, 3), (4, 5, 6)],
      dtype=[('a', '<i8'), ('b', '<i8'), ('c', '<i8')])

In [81]:
data=StringIO(u"1 2 3\n 4 5 6")
np.genfromtxt(data,names="A,B,C")

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

In [82]:
data=StringIO('1 2 3 \n 4 5 6')
ndtype=[('a',int),('b',float),('c',int)]
names=["A","B","C"]
np.genfromtxt(data,names=names,dtype=ndtype)

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('A', '<i8'), ('B', '<f8'), ('C', '<i8')])

In [83]:
#default argument
data=StringIO('1 2 3\n 4 5 6')
np.genfromtxt(data,dtype=(int,float,int))


array([(1, 2., 3), (4, 5., 6)],
      dtype=[('f0', '<i8'), ('f1', '<f8'), ('f2', '<i8')])

In [84]:
import numpy as np

In [85]:
x=np.float32(1.0)

In [86]:
x

1.0

In [87]:
y=np.int_([1,2,4])

In [88]:
y

array([1, 2, 4])

In [89]:
z=np.arange(3,dtype=np.uint8)

In [90]:
z

array([0, 1, 2], dtype=uint8)

In [91]:
a=np.array([1.0,2.0,3.0])
b=np.array([2.0,2.0,2.0])

In [92]:
a*b

array([2., 4., 6.])

In [93]:
b=[2.0]

In [94]:
a*b

array([2., 4., 6.])

In [95]:
x=np.arange(4)

In [97]:
xx=x.reshape(4,1)

In [98]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [99]:
y=np.ones(5)

In [102]:
z=np.ones((3,4))

In [120]:
x+y#mismatch of the shapes in the x+y


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [121]:
xx+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [108]:
xx.shape

(4, 1)

In [109]:
y.shape

(5,)

In [110]:
y

array([1., 1., 1., 1., 1.])

In [111]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [112]:
z.shape

(3, 4)

In [113]:
x+z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [115]:
(x+z).shape

(3, 4)

In [119]:
a=np.array([0.0,10.0,20.0,30.0])
b=np.array([1.0,2.0,3.0])
a[:,np.newaxis]+b#here intially 4*1 axis is there after adding the 3rd axis it converts into 4*3


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])